package dev.mcmateriallist.core.persistence;

public enum StoreStatus {
    OK, MISSING, CORRUPT, UNSUPPORTED_SCHEMA, RECOVERY_REQUIRED, CONFLICT, INVALID_PATH,
    TOO_LARGE, IO_FAILURE, ATOMIC_REPLACE_UNAVAILABLE, BUSY
}
